### ISSUE TITLE
Add Bootstrap v4 support

### ISSUE THREAD

**Issue by rodrigoargumedo** [yrgoldteeth/bootstrap-will_paginate#21]
Although, Bootstrap 4 is in alpha right now but I would like to see some support for the newest framework when it comes out in beta. It looks pretty sick. What do you guys think?

**Comment by delef** [comment]
Bootstrap 4 support here: https://github.com/delef/will_paginate-bootstrap4

**Comment by rodrigoargumedo** [comment]
Dude, that is good repo there! I will use this and find any possible bugs that I may have for you, @delef. Closing.
